cgsnapshot: Fix compiler warnings
Updating to a newer gcc introduced the following warnings.
Fix them :)

	 cgsnapshot.c: In function ‘parse_controllers’:
	cgsnapshot.c:540:53: error: ‘is_ctlr_on_list’ accessing 16777216 bytes in a region of size 409600 [-Werror=stringop-overflow=]
	  540 |                         if ((!(flags & FL_LIST) || (is_ctlr_on_list(controllers, cont_names))) &&
	      |                                                    ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	cgsnapshot.c:540:53: note: referencing argument 2 of type ‘char (*)[4096]’
	cgsnapshot.c:495:12: note: in a call to function ‘is_ctlr_on_list’
	  495 | static int is_ctlr_on_list(char controllers[CG_CONTROLLER_MAX][FILENAME_MAX],
	      |            ^~~~~~~~~~~~~~~
	cgsnapshot.c:560:37: error: ‘is_ctlr_on_list’ accessing 16777216 bytes in a region of size 409600 [-Werror=stringop-overflow=]
	  560 |         if ((!(flags & FL_LIST) || (is_ctlr_on_list(controllers, cont_names))) &&
	      |                                    ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	cgsnapshot.c:560:37: note: referencing argument 2 of type ‘char (*)[4096]’
	cgsnapshot.c:495:12: note: in a call to function ‘is_ctlr_on_list’
	  495 | static int is_ctlr_on_list(char controllers[CG_CONTROLLER_MAX][FILENAME_MAX],
	      |            ^~~~~~~~~~~~~~~

Signed-off-by: Tom Hromatka <tom.hromatka@oracle.com>